language: generic
sudo: false
before_install:
  - evm install $EVM_EMACS --use --skip
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - cask
env:
  - EVM_EMACS=emacs-24.5-travis
script:
  - emacs --version
  - cask list
  - make test
